version: '3.8'

services:
  db:
    image: postgres:15
    container_name: weather_data
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword  # En prod, on utilise un fichier .env
      POSTGRES_DB: weather_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Ce script se lance automatiquement à la création de la base
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: